// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rPartidas_Juego.DAL;

namespace rPartidas_Juego.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200705012335_Partida_Inicial")]
    partial class Partida_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("rPartidas_Juego.Entidades.Jugadores", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("JugadorId");

                    b.ToTable("Jugadores");

                    b.HasData(
                        new
                        {
                            JugadorId = 1,
                            Nombres = "Jose"
                        },
                        new
                        {
                            JugadorId = 2,
                            Nombres = "Luis"
                        },
                        new
                        {
                            JugadorId = 3,
                            Nombres = "Burgos"
                        },
                        new
                        {
                            JugadorId = 4,
                            Nombres = "Hernandez"
                        });
                });

            modelBuilder.Entity("rPartidas_Juego.Entidades.Partidas", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("PartidaId");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("rPartidas_Juego.Entidades.PartidasDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JugadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Posicion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidaId");

                    b.ToTable("PartidasDetalle");
                });

            modelBuilder.Entity("rPartidas_Juego.Entidades.PartidasDetalle", b =>
                {
                    b.HasOne("rPartidas_Juego.Entidades.Jugadores", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rPartidas_Juego.Entidades.Partidas", null)
                        .WithMany("Detalle")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
